version: '3.9'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    build: .
    command: gunicorn birthdays.wsgi:application --bind 0:8000
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - celery_worker
      - celery_beat

  redis:
    image: "redis:latest"
    restart: unless-stopped

  celery_worker:
    build: .
    restart: always
    command: celery -A birthdays worker --loglevel=info
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - redis
      - db
  
  celery_beat:
    build: .
    restart: always
    command: celery -A birthdays beat --loglevel=info
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - redis
      - db

volumes:
  static_value:
  media_value:
  postgres_data: